### ISSUE TITLE
Question/Answer on css/html in elm-reactor obsolete?

### ISSUE THREAD

**Issue by jvoigtlaender** [elm-community/elm-faq#26] opened 2016-07-09 08:43 UTC
Is this:

http://faq.elm-community.org/#how-can-i-load-css-or-other-resources-in-elm-reactor

still accurate, with Elm 0.17.1 released?

Given https://github.com/elm-lang/elm-reactor/commit/36188a21c9c65f91d7bf5cecd5dfe92da524b8d1.

**Comment by fredcy** [comment] 2016-07-11 13:45
I haven't been using elm-reactor and so I can't confirm that the issue is now fixed.

Can someone verify that this issue is resolved and elm-reactor can now serve resource files other than just text?

**Comment by fredcy** [comment] 2016-07-11 14:57
I added text saying that elm-reactor serves resources correctly in Elm 0.17.1.

(Based on discussion in #elm-dev on Slack, since many Elm users may still be running 0.17 it seems best to leave the item in the FAQ for now with the above addendum.)

**Closed as completed by fredcy** 2016-07-11 14:57 UTC
